import React, { useState, useEffect } from "react";
import axios from "axios";
import "./App.css";
import MealList from "./components/MealList";
import MealItem from "./components/MealItems";
import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';
import Navbar from './components/Navbar';
import Home from './components/Home';
import About from './components/About';
import Contact from './components/Contact';
